# [theme]
# backgroundColor="#f9f2f2"
# secondaryBackgroundColor="#f5c5c5"
# textColor="#0e0e0e"

[theme]
primaryColor="#4bffbd"
backgroundColor="#f9f2f2"
secondaryBackgroundColor="#c0ede9"
textColor="#0e0e0e"
